### PR TITLE
2 features merged

### PR DESCRIPTION
**Pull request by Mehek-Shah**
Authentication and Sign in

### CODE REVIEW

**Review by Tennis-Ball — CHANGES_REQUESTED** [review]
Could you revert the Event field names that you kept (ie. where->location, time/date -> start_time+end_time, etc.)? The field names should be descriptive, while the display names (UI) can be more intuitive. 

Also moving forward I think it's best to keep PRs / commits as simple as possible.
ie. Separating backend changes from frontend changes, different feature changes, etc.

Otherwise looks great! I can approve and merge once that change is made repo-wide.

**Comment by Mehek-Shah** [comment]
made the changes requested

**Comment by erikaklam** [comment]
it looks good!

**Comment by Tennis-Ball** [comment]
I'll change the field names later then.

**Pull request merged**
